version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: bicycle_data
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

  data-loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-loader
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    command: ["python", "load_data_to_mysql.py"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-container
    depends_on:
      mysql:
        condition: service_healthy
      data-loader:
        condition: service_started
    networks:
      - app-network
    ports:
      - "5000:5000"
    command: ["sh", "-c", "sleep 10 && python app.py"]

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
